% matlab startup.m
% place in the startup directory for matlab
% creates paths neccessary for ONG-Toolbox
% Change maindir to location of ONG Transmission Simulator
% Seb Savory October 2005

warning off
% Set maindir to your MATLAB directory
maindir = strcat(pwd,'/ONG-Toolbox/');
maindir2 = strcat(pwd,'/Pilot-Toolbox/');
subdirectories={...
    'Active Components'...
    'Analytical Models'...
    'DAC and ADC'...
    'DSP'...
    'Electrical Amplifers'...
    'Electrical Filters'...
    'Examples'...
    'Fibre Propagation'...
    'Functions'...
    'Lab DSP'...
    'Monitors'...
    'Optical Amplifiers'...
    'Optical Filters'...
    'Optical Receiver'...
    'Optimised Function'...
    'Passive Components'...
    'Signal Analysis'...
    'Signal Sources'...
    'WDM Components'};
addpath(maindir)
addpath(maindir2)
for count=1:length(subdirectories)
    directories=addpath([maindir,subdirectories{count}]);
end
warning on

setenv('LC_ALL','C') % Possibly resolves issues with parallel compute toolbox on linux

clear all