function [SignalOut, varargout] = CWLaser(SignalIn, P)
% Creates a continuous wave signal generated by a CW laser with phase noise
%
% Signal=CWLaser(Signal, P)
% If optional arguement P is not included default values are returned
%
% Inputs:
% SignalIn          - Signal structure
% SignalIn.dT       - time resolution [ps]
% 
% Optional Inputs:
% P.Linewidth       - laser linewidth [Hz] default O Hz
% P.Power           - output power [dBm] default is 0 dBm
% P.Offset          - Frequency offset from 1550nm [Hz] default 0 Hz
%
% Returns:
% SignalOut         - output signal structure
%
% Author: Carsten Behrens, October 2008
% Modified: Sean Kilmurray, November 2010
% Modified: Milen Paskov, November 2011

%% Create Parameters
[~, Nt] = size(SignalIn.Et);
[~, TT] = MakeTimeFrequencyArray(SignalIn);
dT = TT(2);

SignalOut = SignalIn;

%% Default Parameters
if nargin == 1;
    P.Linewidth = 0;    % (Hz)
    P.Power = 0;        % (dBm)
    P.Offset = 0;       % (Hz)
else
    if ~isfield(P, 'Power'),
        P.Power = 0;
    end
    if ~isfield(P, 'Offset'),
        P.Offset = 0;
    end
    if ~isfield(P, 'Linewidth'),
        P.Linewidth = 0;
    end
end

%% Create CW
P.CWPower = 10^((P.Power-30)/10);
SignalOut.Et = sqrt(P.CWPower)*exp(-1j*2*pi*TT*P.Offset);

%% Generate Phase Noise
NoiseVariance = 2*pi*dT*P.Linewidth;
% Cumulative phase change
phaseChange = sqrt(NoiseVariance)*cumsum(randn(1,Nt));
SignalOut.Et = SignalOut.Et.*exp(1j*phaseChange);
SignalOut.Et(2,:) = zeros(1, Nt);

P.PhaseNoise = phaseChange;

varargout{1} = P;

%% Verbose
if(isfield(P, 'verbose') && (P.verbose>=1))
    disp(' ');
    disp('Generating a CW Laser');
    disp(['Power: ' num2str(P.Power) 'dBm']);
    disp(['Frequency Offset: ' num2str(P.Offset/1e9) 'GHz']);
    disp(['Laser Linewidth: ' num2str(P.Linewidth/1e6) 'MHz']);
end
end